/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.evozon.evoportal.evozonfreedaysallocator.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BenefitDay service. Represents a row in the &quot;BenefitDay_BenefitDay&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.evozon.evoportal.evozonfreedaysallocator.model.impl.BenefitDayModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.evozon.evoportal.evozonfreedaysallocator.model.impl.BenefitDayImpl}.
 * </p>
 *
 * @author Cristina Kiss
 * @see BenefitDay
 * @see com.evozon.evoportal.evozonfreedaysallocator.model.impl.BenefitDayImpl
 * @see com.evozon.evoportal.evozonfreedaysallocator.model.impl.BenefitDayModelImpl
 * @generated
 */
public interface BenefitDayModel extends BaseModel<BenefitDay> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a benefit day model instance should use the {@link BenefitDay} interface instead.
	 */

	/**
	 * Returns the primary key of this benefit day.
	 *
	 * @return the primary key of this benefit day
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this benefit day.
	 *
	 * @param primaryKey the primary key of this benefit day
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this benefit day.
	 *
	 * @return the entry ID of this benefit day
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this benefit day.
	 *
	 * @param entryId the entry ID of this benefit day
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the type of this benefit day.
	 *
	 * @return the type of this benefit day
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this benefit day.
	 *
	 * @param type the type of this benefit day
	 */
	public void setType(String type);

	/**
	 * Returns the user ID of this benefit day.
	 *
	 * @return the user ID of this benefit day
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this benefit day.
	 *
	 * @param userId the user ID of this benefit day
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this benefit day.
	 *
	 * @return the user uuid of this benefit day
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this benefit day.
	 *
	 * @param userUuid the user uuid of this benefit day
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the days no of this benefit day.
	 *
	 * @return the days no of this benefit day
	 */
	public int getDaysNo();

	/**
	 * Sets the days no of this benefit day.
	 *
	 * @param daysNo the days no of this benefit day
	 */
	public void setDaysNo(int daysNo);

	/**
	 * Returns the allocated date of this benefit day.
	 *
	 * @return the allocated date of this benefit day
	 */
	public Date getAllocatedDate();

	/**
	 * Sets the allocated date of this benefit day.
	 *
	 * @param allocatedDate the allocated date of this benefit day
	 */
	public void setAllocatedDate(Date allocatedDate);

	/**
	 * Returns the comment of this benefit day.
	 *
	 * @return the comment of this benefit day
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this benefit day.
	 *
	 * @param comment the comment of this benefit day
	 */
	public void setComment(String comment);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(BenefitDay benefitDay);

	public int hashCode();

	public CacheModel<BenefitDay> toCacheModel();

	public BenefitDay toEscapedModel();

	public String toString();

	public String toXmlString();
}