/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.evozon.evoportal.evozonfreedaysallocator.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BenefitDayQueue service. Represents a row in the &quot;BenefitDay_BenefitDayQueue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.evozon.evoportal.evozonfreedaysallocator.model.impl.BenefitDayQueueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.evozon.evoportal.evozonfreedaysallocator.model.impl.BenefitDayQueueImpl}.
 * </p>
 *
 * @author Cristina Kiss
 * @see BenefitDayQueue
 * @see com.evozon.evoportal.evozonfreedaysallocator.model.impl.BenefitDayQueueImpl
 * @see com.evozon.evoportal.evozonfreedaysallocator.model.impl.BenefitDayQueueModelImpl
 * @generated
 */
public interface BenefitDayQueueModel extends BaseModel<BenefitDayQueue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a benefit day queue model instance should use the {@link BenefitDayQueue} interface instead.
	 */

	/**
	 * Returns the primary key of this benefit day queue.
	 *
	 * @return the primary key of this benefit day queue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this benefit day queue.
	 *
	 * @param primaryKey the primary key of this benefit day queue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this benefit day queue.
	 *
	 * @return the entry ID of this benefit day queue
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this benefit day queue.
	 *
	 * @param entryId the entry ID of this benefit day queue
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the type of this benefit day queue.
	 *
	 * @return the type of this benefit day queue
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this benefit day queue.
	 *
	 * @param type the type of this benefit day queue
	 */
	public void setType(String type);

	/**
	 * Returns the user ID of this benefit day queue.
	 *
	 * @return the user ID of this benefit day queue
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this benefit day queue.
	 *
	 * @param userId the user ID of this benefit day queue
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this benefit day queue.
	 *
	 * @return the user uuid of this benefit day queue
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this benefit day queue.
	 *
	 * @param userUuid the user uuid of this benefit day queue
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the days no of this benefit day queue.
	 *
	 * @return the days no of this benefit day queue
	 */
	public int getDaysNo();

	/**
	 * Sets the days no of this benefit day queue.
	 *
	 * @param daysNo the days no of this benefit day queue
	 */
	public void setDaysNo(int daysNo);

	/**
	 * Returns the queued of this benefit day queue.
	 *
	 * @return the queued of this benefit day queue
	 */
	public boolean getQueued();

	/**
	 * Returns <code>true</code> if this benefit day queue is queued.
	 *
	 * @return <code>true</code> if this benefit day queue is queued; <code>false</code> otherwise
	 */
	public boolean isQueued();

	/**
	 * Sets whether this benefit day queue is queued.
	 *
	 * @param queued the queued of this benefit day queue
	 */
	public void setQueued(boolean queued);

	/**
	 * Returns the added date of this benefit day queue.
	 *
	 * @return the added date of this benefit day queue
	 */
	public Date getAddedDate();

	/**
	 * Sets the added date of this benefit day queue.
	 *
	 * @param addedDate the added date of this benefit day queue
	 */
	public void setAddedDate(Date addedDate);

	/**
	 * Returns the allocated date of this benefit day queue.
	 *
	 * @return the allocated date of this benefit day queue
	 */
	public Date getAllocatedDate();

	/**
	 * Sets the allocated date of this benefit day queue.
	 *
	 * @param allocatedDate the allocated date of this benefit day queue
	 */
	public void setAllocatedDate(Date allocatedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(BenefitDayQueue benefitDayQueue);

	public int hashCode();

	public CacheModel<BenefitDayQueue> toCacheModel();

	public BenefitDayQueue toEscapedModel();

	public String toString();

	public String toXmlString();
}