/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.evozon.evoportal.evozonfreedaysallocator.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FreeDaysHistoryEntry service. Represents a row in the &quot;BenefitDay_FreeDaysHistoryEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.evozon.evoportal.evozonfreedaysallocator.model.impl.FreeDaysHistoryEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.evozon.evoportal.evozonfreedaysallocator.model.impl.FreeDaysHistoryEntryImpl}.
 * </p>
 *
 * @author Cristina Kiss
 * @see FreeDaysHistoryEntry
 * @see com.evozon.evoportal.evozonfreedaysallocator.model.impl.FreeDaysHistoryEntryImpl
 * @see com.evozon.evoportal.evozonfreedaysallocator.model.impl.FreeDaysHistoryEntryModelImpl
 * @generated
 */
public interface FreeDaysHistoryEntryModel extends BaseModel<FreeDaysHistoryEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a free days history entry model instance should use the {@link FreeDaysHistoryEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this free days history entry.
	 *
	 * @return the primary key of this free days history entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this free days history entry.
	 *
	 * @param primaryKey the primary key of this free days history entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this free days history entry.
	 *
	 * @return the entry ID of this free days history entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this free days history entry.
	 *
	 * @param entryId the entry ID of this free days history entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the user ID of this free days history entry.
	 *
	 * @return the user ID of this free days history entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this free days history entry.
	 *
	 * @param userId the user ID of this free days history entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this free days history entry.
	 *
	 * @return the user uuid of this free days history entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this free days history entry.
	 *
	 * @param userUuid the user uuid of this free days history entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the operation of this free days history entry.
	 *
	 * @return the operation of this free days history entry
	 */
	@AutoEscape
	public String getOperation();

	/**
	 * Sets the operation of this free days history entry.
	 *
	 * @param operation the operation of this free days history entry
	 */
	public void setOperation(String operation);

	/**
	 * Returns the old value of this free days history entry.
	 *
	 * @return the old value of this free days history entry
	 */
	public int getOldValue();

	/**
	 * Sets the old value of this free days history entry.
	 *
	 * @param oldValue the old value of this free days history entry
	 */
	public void setOldValue(int oldValue);

	/**
	 * Returns the days no of this free days history entry.
	 *
	 * @return the days no of this free days history entry
	 */
	public int getDaysNo();

	/**
	 * Sets the days no of this free days history entry.
	 *
	 * @param daysNo the days no of this free days history entry
	 */
	public void setDaysNo(int daysNo);

	/**
	 * Returns the new value of this free days history entry.
	 *
	 * @return the new value of this free days history entry
	 */
	public int getNewValue();

	/**
	 * Sets the new value of this free days history entry.
	 *
	 * @param newValue the new value of this free days history entry
	 */
	public void setNewValue(int newValue);

	/**
	 * Returns the create date of this free days history entry.
	 *
	 * @return the create date of this free days history entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this free days history entry.
	 *
	 * @param createDate the create date of this free days history entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the event type of this free days history entry.
	 *
	 * @return the event type of this free days history entry
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this free days history entry.
	 *
	 * @param eventType the event type of this free days history entry
	 */
	public void setEventType(String eventType);

	/**
	 * Returns the description of this free days history entry.
	 *
	 * @return the description of this free days history entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this free days history entry.
	 *
	 * @param description the description of this free days history entry
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FreeDaysHistoryEntry freeDaysHistoryEntry);

	public int hashCode();

	public CacheModel<FreeDaysHistoryEntry> toCacheModel();

	public FreeDaysHistoryEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}