/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.evozon.evoportal.evozonfreedaysallocator.service.base;

import com.evozon.evoportal.evozonfreedaysallocator.model.BenefitDay;
import com.evozon.evoportal.evozonfreedaysallocator.service.BenefitDayLocalService;
import com.evozon.evoportal.evozonfreedaysallocator.service.BenefitDayQueueLocalService;
import com.evozon.evoportal.evozonfreedaysallocator.service.FreeDaysHistoryEntryLocalService;
import com.evozon.evoportal.evozonfreedaysallocator.service.persistence.BenefitDayPersistence;
import com.evozon.evoportal.evozonfreedaysallocator.service.persistence.BenefitDayQueuePersistence;
import com.evozon.evoportal.evozonfreedaysallocator.service.persistence.FreeDaysHistoryEntryPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the benefit day local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.evozon.evoportal.evozonfreedaysallocator.service.impl.BenefitDayLocalServiceImpl}.
 * </p>
 *
 * @author Cristina Kiss
 * @see com.evozon.evoportal.evozonfreedaysallocator.service.impl.BenefitDayLocalServiceImpl
 * @see com.evozon.evoportal.evozonfreedaysallocator.service.BenefitDayLocalServiceUtil
 * @generated
 */
public abstract class BenefitDayLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements BenefitDayLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.evozon.evoportal.evozonfreedaysallocator.service.BenefitDayLocalServiceUtil} to access the benefit day local service.
	 */

	/**
	 * Adds the benefit day to the database. Also notifies the appropriate model listeners.
	 *
	 * @param benefitDay the benefit day
	 * @return the benefit day that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public BenefitDay addBenefitDay(BenefitDay benefitDay)
		throws SystemException {
		benefitDay.setNew(true);

		return benefitDayPersistence.update(benefitDay, false);
	}

	/**
	 * Creates a new benefit day with the primary key. Does not add the benefit day to the database.
	 *
	 * @param entryId the primary key for the new benefit day
	 * @return the new benefit day
	 */
	public BenefitDay createBenefitDay(long entryId) {
		return benefitDayPersistence.create(entryId);
	}

	/**
	 * Deletes the benefit day with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param entryId the primary key of the benefit day
	 * @return the benefit day that was removed
	 * @throws PortalException if a benefit day with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public BenefitDay deleteBenefitDay(long entryId)
		throws PortalException, SystemException {
		return benefitDayPersistence.remove(entryId);
	}

	/**
	 * Deletes the benefit day from the database. Also notifies the appropriate model listeners.
	 *
	 * @param benefitDay the benefit day
	 * @return the benefit day that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public BenefitDay deleteBenefitDay(BenefitDay benefitDay)
		throws SystemException {
		return benefitDayPersistence.remove(benefitDay);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(BenefitDay.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return benefitDayPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return benefitDayPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return benefitDayPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return benefitDayPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public BenefitDay fetchBenefitDay(long entryId) throws SystemException {
		return benefitDayPersistence.fetchByPrimaryKey(entryId);
	}

	/**
	 * Returns the benefit day with the primary key.
	 *
	 * @param entryId the primary key of the benefit day
	 * @return the benefit day
	 * @throws PortalException if a benefit day with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public BenefitDay getBenefitDay(long entryId)
		throws PortalException, SystemException {
		return benefitDayPersistence.findByPrimaryKey(entryId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return benefitDayPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the benefit daies.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of benefit daies
	 * @param end the upper bound of the range of benefit daies (not inclusive)
	 * @return the range of benefit daies
	 * @throws SystemException if a system exception occurred
	 */
	public List<BenefitDay> getBenefitDaies(int start, int end)
		throws SystemException {
		return benefitDayPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of benefit daies.
	 *
	 * @return the number of benefit daies
	 * @throws SystemException if a system exception occurred
	 */
	public int getBenefitDaiesCount() throws SystemException {
		return benefitDayPersistence.countAll();
	}

	/**
	 * Updates the benefit day in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param benefitDay the benefit day
	 * @return the benefit day that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public BenefitDay updateBenefitDay(BenefitDay benefitDay)
		throws SystemException {
		return updateBenefitDay(benefitDay, true);
	}

	/**
	 * Updates the benefit day in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param benefitDay the benefit day
	 * @param merge whether to merge the benefit day with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the benefit day that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public BenefitDay updateBenefitDay(BenefitDay benefitDay, boolean merge)
		throws SystemException {
		benefitDay.setNew(false);

		return benefitDayPersistence.update(benefitDay, merge);
	}

	/**
	 * Returns the benefit day local service.
	 *
	 * @return the benefit day local service
	 */
	public BenefitDayLocalService getBenefitDayLocalService() {
		return benefitDayLocalService;
	}

	/**
	 * Sets the benefit day local service.
	 *
	 * @param benefitDayLocalService the benefit day local service
	 */
	public void setBenefitDayLocalService(
		BenefitDayLocalService benefitDayLocalService) {
		this.benefitDayLocalService = benefitDayLocalService;
	}

	/**
	 * Returns the benefit day persistence.
	 *
	 * @return the benefit day persistence
	 */
	public BenefitDayPersistence getBenefitDayPersistence() {
		return benefitDayPersistence;
	}

	/**
	 * Sets the benefit day persistence.
	 *
	 * @param benefitDayPersistence the benefit day persistence
	 */
	public void setBenefitDayPersistence(
		BenefitDayPersistence benefitDayPersistence) {
		this.benefitDayPersistence = benefitDayPersistence;
	}

	/**
	 * Returns the benefit day queue local service.
	 *
	 * @return the benefit day queue local service
	 */
	public BenefitDayQueueLocalService getBenefitDayQueueLocalService() {
		return benefitDayQueueLocalService;
	}

	/**
	 * Sets the benefit day queue local service.
	 *
	 * @param benefitDayQueueLocalService the benefit day queue local service
	 */
	public void setBenefitDayQueueLocalService(
		BenefitDayQueueLocalService benefitDayQueueLocalService) {
		this.benefitDayQueueLocalService = benefitDayQueueLocalService;
	}

	/**
	 * Returns the benefit day queue persistence.
	 *
	 * @return the benefit day queue persistence
	 */
	public BenefitDayQueuePersistence getBenefitDayQueuePersistence() {
		return benefitDayQueuePersistence;
	}

	/**
	 * Sets the benefit day queue persistence.
	 *
	 * @param benefitDayQueuePersistence the benefit day queue persistence
	 */
	public void setBenefitDayQueuePersistence(
		BenefitDayQueuePersistence benefitDayQueuePersistence) {
		this.benefitDayQueuePersistence = benefitDayQueuePersistence;
	}

	/**
	 * Returns the free days history entry local service.
	 *
	 * @return the free days history entry local service
	 */
	public FreeDaysHistoryEntryLocalService getFreeDaysHistoryEntryLocalService() {
		return freeDaysHistoryEntryLocalService;
	}

	/**
	 * Sets the free days history entry local service.
	 *
	 * @param freeDaysHistoryEntryLocalService the free days history entry local service
	 */
	public void setFreeDaysHistoryEntryLocalService(
		FreeDaysHistoryEntryLocalService freeDaysHistoryEntryLocalService) {
		this.freeDaysHistoryEntryLocalService = freeDaysHistoryEntryLocalService;
	}

	/**
	 * Returns the free days history entry persistence.
	 *
	 * @return the free days history entry persistence
	 */
	public FreeDaysHistoryEntryPersistence getFreeDaysHistoryEntryPersistence() {
		return freeDaysHistoryEntryPersistence;
	}

	/**
	 * Sets the free days history entry persistence.
	 *
	 * @param freeDaysHistoryEntryPersistence the free days history entry persistence
	 */
	public void setFreeDaysHistoryEntryPersistence(
		FreeDaysHistoryEntryPersistence freeDaysHistoryEntryPersistence) {
		this.freeDaysHistoryEntryPersistence = freeDaysHistoryEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.evozon.evoportal.evozonfreedaysallocator.model.BenefitDay",
			benefitDayLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.evozon.evoportal.evozonfreedaysallocator.model.BenefitDay");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return BenefitDay.class;
	}

	protected String getModelClassName() {
		return BenefitDay.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = benefitDayPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = BenefitDayLocalService.class)
	protected BenefitDayLocalService benefitDayLocalService;
	@BeanReference(type = BenefitDayPersistence.class)
	protected BenefitDayPersistence benefitDayPersistence;
	@BeanReference(type = BenefitDayQueueLocalService.class)
	protected BenefitDayQueueLocalService benefitDayQueueLocalService;
	@BeanReference(type = BenefitDayQueuePersistence.class)
	protected BenefitDayQueuePersistence benefitDayQueuePersistence;
	@BeanReference(type = FreeDaysHistoryEntryLocalService.class)
	protected FreeDaysHistoryEntryLocalService freeDaysHistoryEntryLocalService;
	@BeanReference(type = FreeDaysHistoryEntryPersistence.class)
	protected FreeDaysHistoryEntryPersistence freeDaysHistoryEntryPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private BenefitDayLocalServiceClpInvoker _clpInvoker = new BenefitDayLocalServiceClpInvoker();
}